# Generated by Django 4.1.4 on 2023-05-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(default='touriste', max_length=255)),
                ('password', models.CharField(max_length=63)),
                ('firstname', models.CharField(max_length=63)),
                ('lastname', models.CharField(max_length=63)),
            ],
        ),
    ]
