# Generated by Django 4.1.4 on 2023-05-27 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizer',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='utilizer',
            name='lastname',
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=63)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.utilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('category', models.CharField(max_length=63)),
                ('theme', models.CharField(blank=True, max_length=63, null=True)),
                ('description', models.TextField(blank=True, max_length=4064, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('datefrom', models.DateTimeField(blank=True, null=True)),
                ('dateto', models.DateTimeField(blank=True, null=True)),
                ('idRegion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region')),
                ('idUtilizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.utilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('idPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.place')),
            ],
        ),
    ]
