# Generated by Django 4.1.4 on 2023-05-27 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_firstname_utilizer_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2023, 5, 27, 6, 31, 26, 551744, tzinfo=datetime.timezone.utc))),
                ('comment', models.TextField(blank=True, max_length=4064, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('idPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.place')),
                ('idUtilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
                ('idUtilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.utilizer')),
            ],
        ),
    ]
