# Generated by Django 4.1.4 on 2023-06-15 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2023, 6, 15, 9, 15, 47, 120511, tzinfo=datetime.timezone.utc))),
                ('comment', models.TextField(blank=True, max_length=4064, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('idPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.place')),
                ('idUtilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('idPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.place')),
                ('idUtilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilizer')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
