# Generated by Django 4.1.4 on 2023-06-15 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_rating_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 9, 52, 36, 117302, tzinfo=datetime.timezone.utc)),
        ),
    ]
