# Generated by Django 4.1.4 on 2023-06-15 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comment_pubdate_transport_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 23, 51, 1, 277273, tzinfo=datetime.timezone.utc)),
        ),
    ]
